### ISSUE TITLE
p/doseq

### ISSUE THREAD

**Issue by borkdude** [funcool/promesa#112]
I often find users trying to use `doseq` with promises which isn't a good combination since `doseq` is synchronous.
Perhaps it's possible to come up with a promesa-variant of this.

**Comment by niwinz** [comment]
what is use case? I mean I use promesa extensively and never needed it. An example would be awesome.

**Comment by borkdude** [comment]
E.g.:

```
(let [links ["https://foobar.net" "https://foobar.com"]]
  (doseq [l link]
    (playwright/screenshot l #js {:path "/tmp/screenshot.png"})))
```

Using `p/doseq` these things would actually happen in serial.

Perhaps there's already another way to do this. `p/loop` is one of them.

I'm also pinging @joe-loco here who was running into this today.

**Comment by niwinz** [comment]
Yeah, I understand.

I'm happy to accept a PR for the promises aware doseq.

**Comment by borkdude** [comment]
One problem with `doseq` is that the expansion is pretty involved because you can have multiple bindings and `:when` and `:let` but 99% of the time people use only one binding + seq.
This is an implementation in user space:

```
(ns doseq
  {:clj-kondo/config '{:lint-as {doseq/pdoseq clojure.core/doseq}}}
  (:require [promesa.core :as p]))

(defmacro pdoseq
  "Simplified version of `doseq` which takes one binding and a seq, and
  runs over it using `prun!`."
  [[binding xs] & body]
  `(p/run! (fn [~binding]
               (p/do ~@body))
           ~xs))

(pdoseq [x [1 2 3]]
        (prn x)
        (p/delay 1000))
```

I'd personally be fine with this limited version, but it might raise the expectation that it supports of all `doseq`.

**Comment by niwinz** [comment]
I'm pretty fine with the limited version. I think I have never used the all the other stuff of doseq and I tend to replace it with run! all the times on my code for performance reasons.

**Comment by niwinz** [comment]
So with your permission, I will take this doseq impl for promesa.

**Comment by borkdude** [comment]
Yeah. As long as the docstring documents the limitation, I think it's fine.

**Comment by borkdude** [comment]
I'll provide a PR

**Comment by borkdude** [comment]
@niwinz See PR. I noticed (or rather clj-kondo noticed) that there was an unused value here:

https://github.com/borkdude/promesa/commit/3b9b92fff513b7b08a9349a32848062d43dbdca3#diff-3252c28c90776426b8ed0bd8100b3c709cba322ef141909ac3fec13e6ba2839bR493

**Comment by borkdude** [comment]
Perhaps the unused value was intended to wrapped in a test assertion?
