### ISSUE TITLE
ClojureScript compilation error with 9.0.489

### ISSUE THREAD

**Issue by aviflat** [funcool/promesa#121]
I tend to update my deps regularly. I just tried updating my ClojureScript project to the latest release 9.0.489 and I’m getting a compilation error. When I roll back to 9.0.477 it compiles successfully.

```text
[:my-project] Compiling ...
------ ERROR -------------------------------------------------------------------
 File: /Users/avi/.gitlibs/libs/com.github.funcool/promesa/3e925658ca31dfab94fdec1d82b9e7a1184185d1/src/promesa/core.cljc
failed to require macro-ns "promesa.core", it was required by "promesa.core"
Error in phase :execution
ClassNotFoundException: promesa.exec.ConcurrencyLimiter
```

<details><summary>the error with the full stack trace</summary>

```text
[:my-project] Compiling ...
------ ERROR -------------------------------------------------------------------
 File: /Users/avi/.gitlibs/libs/com.github.funcool/promesa/3e925658ca31dfab94fdec1d82b9e7a1184185d1/src/promesa/core.cljc
failed to require macro-ns "promesa.core", it was required by "promesa.core"
Error in phase :execution
ClassNotFoundException: promesa.exec.ConcurrencyLimiter
	java.net.URLClassLoader.findClass (URLClassLoader.java:445)
	clojure.lang.DynamicClassLoader.findClass (DynamicClassLoader.java:69)
	java.lang.ClassLoader.loadClass (ClassLoader.java:587)
	clojure.lang.DynamicClassLoader.loadClass (DynamicClassLoader.java:77)
	java.lang.ClassLoader.loadClass (ClassLoader.java:520)
	java.lang.Class.forName0 (Class.java:-2)
	java.lang.Class.forName (Class.java:467)
	clojure.lang.RT.classForName (RT.java:2209)
	clojure.lang.RT.classForNameNonLoading (RT.java:2222)
	promesa.exec/eval22106/loading--6789--auto----22107 (exec.cljc:7)
	promesa.exec/eval22106 (exec.cljc:7)
	promesa.exec/eval22106 (exec.cljc:7)
	clojure.lang.Compiler.eval (Compiler.java:7194)
	clojure.lang.Compiler.eval (Compiler.java:7183)
	clojure.lang.Compiler.load (Compiler.java:7653)
	clojure.lang.RT.loadResourceScript (RT.java:381)
	clojure.lang.RT.loadResourceScript (RT.java:372)
	clojure.lang.RT.load (RT.java:459)
	clojure.lang.RT.load (RT.java:424)
	clojure.core/load/fn--6908 (core.clj:6161)
	clojure.core/load (core.clj:6160)
	clojure.core/load (core.clj:6144)
	clojure.core/load-one (core.clj:5933)
	clojure.core/load-one (core.clj:5928)
	clojure.core/load-lib/fn--6850 (core.clj:5975)
	clojure.core/load-lib (core.clj:5974)
	clojure.core/load-lib (core.clj:5953)
	clojure.core/apply (core.clj:669)
	clojure.core/load-libs (core.clj:6016)
	clojure.core/load-libs (core.clj:6000)
	clojure.core/apply (core.clj:669)
	clojure.core/require (core.clj:6038)
	clojure.core/require (core.clj:6038)
	promesa.core/eval21594/loading--6789--auto----21595 (core.cljc:7)
	promesa.core/eval21594 (core.cljc:7)
	promesa.core/eval21594 (core.cljc:7)
	clojure.lang.Compiler.eval (Compiler.java:7194)
	clojure.lang.Compiler.eval (Compiler.java:7183)
	clojure.lang.Compiler.load (Compiler.java:7653)
	clojure.lang.RT.loadResourceScript (RT.java:381)
	clojure.lang.RT.loadResourceScript (RT.java:372)
	clojure.lang.RT.load (RT.java:459)
	clojure.lang.RT.load (RT.java:424)
	clojure.core/load/fn--6908 (core.clj:6161)
	clojure.core/load (core.clj:6160)
	clojure.core/load (core.clj:6144)
	clojure.core/load-one (core.clj:5933)
	clojure.core/load-one (core.clj:5928)
	clojure.core/load-lib/fn--6850 (core.clj:5975)
	clojure.core/load-lib (core.clj:5974)
	clojure.core/load-lib (core.clj:5953)
	clojure.core/apply (core.clj:669)
	clojure.core/load-libs (core.clj:6016)
	clojure.core/load-libs (core.clj:6000)
	clojure.core/apply (core.clj:669)
	clojure.core/require (core.clj:6038)
	clojure.core/require (core.clj:6038)
	shadow.build.macros/load-macros/fn--14932/fn--14943 (macros.clj:101)
	shadow.build.macros/load-macros/fn--14932 (macros.clj:100)
	shadow.build.macros/load-macros (macros.clj:94)
	shadow.build.macros/load-macros (macros.clj:85)
	shadow.build.compiler/post-analyze-ns (compiler.clj:49)
	shadow.build.compiler/post-analyze-ns (compiler.clj:46)
	shadow.build.compiler/post-analyze (compiler.clj:92)
	shadow.build.compiler/post-analyze (compiler.clj:89)
	shadow.build.compiler/analyze/fn--15079 (compiler.clj:265)
	shadow.build.compiler/analyze (compiler.clj:252)
	shadow.build.compiler/analyze (compiler.clj:211)
	shadow.build.compiler/analyze (compiler.clj:213)
	shadow.build.compiler/analyze (compiler.clj:211)
	shadow.build.compiler/default-analyze-cljs (compiler.clj:415)
	shadow.build.compiler/default-analyze-cljs (compiler.clj:404)
	clojure.core/partial/fn--5908 (core.clj:2642)
	shadow.build.compiler/do-analyze-cljs-string (compiler.clj:321)
	shadow.build.compiler/do-analyze-cljs-string (compiler.clj:278)
	shadow.build.compiler/analyze-cljs-string/fn--15174 (compiler.clj:518)
	shadow.build.compiler/analyze-cljs-string (compiler.clj:517)
	shadow.build.compiler/analyze-cljs-string (compiler.clj:515)
	shadow.build.compiler/do-compile-cljs-resource/fn--15202 (compiler.clj:633)
	shadow.build.compiler/do-compile-cljs-resource (compiler.clj:614)
```

</details>

I’m proficient with JVM Clojure but fairly new to CLJS and don’t quite understand how it works, nor all the things that Shadow does. So maybe I’ve got something set up wrong in my project?

#### some snippets from my `deps.edn`

```clojure
{:deps
 {com.github.funcool/promesa {:git/sha "3e925658" :git/tag "9.0.489"}
  thheller/shadow-cljs {:mvn/version "2.20.6"}}}
```

I’ve got the same version of shadow-cljs in my `node_modules` via npm.

#### a snippet from my `shadow-cljs.edn`

My shadow build is pretty simple, I think:

```
{:deps true
 :builds {:my-project {:compiler-options {:warnings-as-errors true
                                     :warnings {:fn-arity true}}
                  :target :node-library
...
```

**Comment by niwinz** [comment]
I will look on it next Monday (I'm out for holidays right now, hehe).

Looks like a bug in promesa at first glass but i need to look it properly
for understand correctly what is happening 🙂

**Comment by niwinz** [comment]
Oh, after taking a look again..., try to require it from mvn/clojars
instead of git dep.

This error happens because in the latest version ConcurrencyLimiter type is
added as java file, and the compiled class file is only found on the jar
deployed on clojars.

I have plans to reimplement it in multiplatform way, but right now it is
implemented in java directly.

I didn't expected that this library is used as git dep, knowing that, I can
consider upload the class files directly to GitHub for make it work also
for cases whe promesa is used as git dep.

**Comment by aviflat** [comment]
@niwinz thanks so much for the rapid and cogent response! It’s good to understand the problem here, and to have a workaround.

That said, I do greatly prefer to use Clojure/Script libraries as gitlibs, and Promesa _was_ working that way for a good while, so if there is some way to restore that capability, that’d be excellent. Please let me know how I can help! Perhaps a PR adding a GitHub Actions job or workflow that would test this capability for both JVM Clojure and ClojureScript would be helpful?

**Comment by niwinz** [comment]
El jue., 27 oct. 2022 17:33, Avi Flax @ Latacora ***@***.***>
escribió:

> @niwinz <https://github.com/niwinz> thanks so much for the rapid and
> cogent response! It’s good to understand the problem here, and to have a
> workaround.
>
> That said, I do greatly prefer to use Clojure/Script libraries as gitlibs,
> and Promesa *was* working that way for a good while, so if there is some
> way to restore that capability, that’d be excellent. Please let me know how
> I can help! Perhaps a PR adding a GitHub Actions job or workflow that would
> test this capability for both JVM Clojure and ClojureScript would be
> helpful?
>


Yep, that will be welcome!
Thanks

**Comment by niwinz** [comment]
I will fix it in the next releases to give back the ability to use it as
git dep.

**Comment by niwinz** [comment]
The latest tag should work as git dep

**Comment by aviflat** [comment]
@niwinz I tested the latest tag ([9.0.493](https://github.com/funcool/promesa/releases/tag/9.0.493)) and it does indeed seem to work again as a gitdep. Thanks so much!

**Comment by aviflat** [comment]
@niwinz sorry, it looks like I spoke too soon. I updated the version in my `deps.edn` and my tests passed, but then they failed in my CD environment. Turns out I had some stale state in my local `.shadow-cljs` dir and/or my local shadow-cljs compilation server. Once I killed those to clear out that state, I found that there is still a class missing:

```
[:test] Compiling ...
------ ERROR -------------------------------------------------------------------
 File: /Users/avi/.gitlibs/libs/com.github.funcool/promesa/eea6c76d7d6a826813778f61588e2188c01b9917/src/promesa/core.cljc
failed to require macro-ns "promesa.core", it was required by "promesa.core"
Error in phase :compile-syntax-check
NoClassDefFoundError: promesa/exec/ConcurrencyLimiter$CapacityLimitReachedException
```

…so maybe you missed copying that class file into the right spot in the repo?

Thanks again for the help!

**Comment by niwinz** [comment]
try the 9.0.494, it should contain all the classes, sorry for noise

**Comment by aviflat** [comment]
That did it! Thank you!
