### ISSUE TITLE
promisify vs. bluebird's promisify

### ISSUE THREAD

**Issue by moea** [funcool/promesa#13]
The docstring for `promisify` mentions it converts functions taking Node-style callbacks, though the Node convention is (error, result).  Bluebird's [Promise.promisify](http://bluebirdjs.com/docs/api/promise.promisify.html) is aware of this, and will reject the promise if the injected function is passed an error, otherwise resolve w/ the second arg. 

If the intention is to only support callbacks which use a single parameter, maybe it'd be clearer if the comment were adjusted to not mention Node.  Or else adjust/add a different utility for cross-platform two argument promisification.  More than happy to submit a PR if you think a change is justified.

(I personally only have a need for this functionality in Clojurescript, so I'm using (.promisify js/Promise ...) directly - It'd be a tiny bit easier for me to have that be (p/promisify ...), but I'm not sure what's best for the library)

**Comment by niwinz** [comment]
I know about promisify and its awareness of node context, but promesa works in two different platforms and implement promisify differently for each platform is not convincing me...

**Comment by moea** [comment]
That makes sense - the docstring for the function led me to believe it was trying to do something else.

**Comment by jetmind** [comment]
I hit the same today. I think docstring should be changed to something less misleading if supporting `(error, result)` kind of promises isn't an option.

**Comment by niwinz** [comment]
PR is very welcome!

**Comment by jetmind** [comment]
Rephrased docstring as best as I could to make it clearer in #18. I'm open to suggestions if it's not clear enough.

**Comment by simshanith** [comment]
If I have time I may turn this into a PR, but here's how I implemented a similar function:

```clojure
(defn node-promisify
  "Promisify a Node method.
   Comparable to [Bluebird's `promisify` method](http://bluebirdjs.com/docs/api/promise.promisify.html).
   Accepts a method that uses its last argument as callback with an error (or null upon success) as the callback's first argument.
   Returns the promisified success values as a seq."
  ([node-method]
    (node-promisify node-method {}))
  ([node-method {:keys [context] :as options}]
    (fn [& all]
      (p/promise (fn [resolve reject]
        (let [callback (fn [err & results]
                (if (nil? err)
                  (resolve results)
                  (reject err)))
              method-args (clj->js (conj (vec all) callback))]
          (.apply node-method context method-args)))))))
```

Note that it always resolves in `multiArgs` fashion compared to Bluebird's `promisify`. To resolve with only the first success argument, instead of a `seq`:

```clojure
(let [promisified (node-promisify js/nodebackExample)]
  (-> (promisified)
      (p/then first)))
```

Note that the promisified function does not accept a callback argument - callbacks must be attached via promesa, and should be omitted from the promisified invocation arguments.
