### ISSUE TITLE
cljdoc broken

### ISSUE THREAD

**Issue by hukka** [funcool/promesa#130]
https://cljdoc.org/d/funcool/promesa/ is broken, likely because https://github.com/funcool/promesa/blob/master/doc/cljdoc.edn#L1 refers to non-existing file: https://cljdoc.org/builds/64183, removed in https://github.com/funcool/promesa/commit/f924e98d97f71ac00bd9c01553f3d1bf78fcb789

**Comment by niwinz** [comment]
Thanks, solved
