### ISSUE TITLE
`promise-buffer` in `promesa.exec.csp.buffers`?

### ISSUE THREAD

**Issue by fr33m0nk** [funcool/promesa#131]
Hi there,

I was exploring the possibility of adding a `promise-chan` using `promesa.exec.csp.buffers`

The implementation can look like 

```clojure
(defn promise
  []
  (let [buf (mlist/create)]
    (reify
      pt/IBuffer
      (-full? [_] false)
      (-poll! [this]
        (first buf))
      (-offer! [this o]
        (if (> (mlist/size buf) 0)
          buf
          (mlist/add-first! buf o)))
      (-size [_]
        (mlist/size buf)))))
```

Limited testing shows it works as expected with one caveat:

```clojure
(def a (chan (buffers/promise)))
;;=> #'promesa.exec.csp/a

;; Promise channels only put! a single value on channel, but keep returning the same value all the time
(put! a 10)
;;=> true

(take! a)
;;=> 10
(take! a)
;;=> 10
(take! a)
;;=> 10

;; putting in new value is without effect, again as expected
(put! a 20)
;;=> true

(take! a)
=> 10
```

Caveat:
`core.async` promise-channels when closed, returns `nil` on `take!`. 
Above implementation, however, keeps on returning the value which was `put!` e.g.

```clojure
(close! a)
;;=> nil
(take! a)
;;=> 10

```

I would greatly appreciate few pointers.
Let me know in case something like `promise-buffer` is needed in Promesa. I am happy to do a PR :)

**Comment by niwinz** [comment]
Hello @fr33m0nk 

hmm, interesting.

I guess it does not works as expected is because the close flag of channel is not the same for the buffer.
Let me play a bit with it and I give you a feedback on it.

In any case, I have a question here? ¿Is it really useful? the promise-chan/promise-buffer i mean. 

What is the use case?, personally I never understood the core.async promise-chan purpose. From my point of view there are CompletableFuture that is a good abstraction for represent the promise abstraction...

**Comment by niwinz** [comment]
ok after looking on it, the main difference with core.async is that in promesa, buffers does  not implement the -close! method
This is the mechanism used by core.async for return nil after closing.
I don't have any problem on implement close for all buffers if it helps for this; I think this is the missing piece for implement it in the same way as core.async

**Comment by niwinz** [comment]
https://github.com/funcool/promesa/commit/9fa184851a0e4e21600b027566e89731d7efe530 here working implementation

**Comment by niwinz** [comment]
I guess we can close this, right now I have pushed a version 10.0.582, with that changes, you can experiment with that. If you think we need more public api, feel free to reopen or open an other issue. Any feedback on it is very welcome!
