### ISSUE TITLE
Example in README fails in ClojureScript

### ISSUE THREAD

**Issue by rome-user** [funcool/promesa#134]
I want to try using this library, but it's hard to tell what works in ClojureScript.
```
cljs.user> (require '[promesa.core :as p])
nil
cljs.user> (->> (p/promise 1)
                (p/map inc)
                (deref))

Execution error (Error) at (<cljs repl>:1).
No protocol method IDeref.-deref defined for type object: [object Promise]
:repl/exception!
```

For reference, I am running:
* Node.js 18.13.0
* ClojureScript 1.11.60
* shadow-cljs 2.20.20
* promesa 10.0.571

**Comment by niwinz** [comment]
Yep, this is because the example is JVM only, CLJS does not support synchronous blocking operations
