### ISSUE TITLE
Optimizations advanced Uncaught TypeError: Cannot set property '_bitField' of undefined (possible dependency problem)

### ISSUE THREAD

**Issue by kennyjwilli** [funcool/promesa#23]
Previously created https://github.com/funcool/httpurr/issues/8 but moved to here.

Create a namespace similar to the below and compile it using `:optimizations :advanced`. Run the main function and in a browser and you will see an error that says `Uncaught TypeError: Cannot set property '_bitField' of undefined`.

```clojure
(ns bitfield-error.core
  (:require [cognitect.transit :as t]
            [httpurr.client :as http]))

(enable-console-print!)

(defn encode
  [data]
  (let [w (t/writer :json)]
    (t/write w data)))

(defn ^:export main
  []
  (println "encoded" (encode {:foo "bar"})))
```

Now comment out the :require containing `[httpurr.client :as http]`, refresh the browser, and you should see encoded `["^ ","~:foo","bar"]` printed to the console (no error).

I have created a minimal working example here: https://github.com/kennyjwilli/bitfield-error. See the README for more info on how to use the project.

**Comment by kennyjwilli** [comment]
Also note that this error **only** occurs when using `:optimizations :advanced` .

**Comment by niwinz** [comment]
Thank you very much! 
The test project will help a lot for try to solve it ;)

**Comment by niwinz** [comment]
Fixed
