### ISSUE TITLE
Cannot compile in cljs - reserved words error

### ISSUE THREAD

**Issue by mattly** [funcool/promesa#24]
I'm getting the following warnings when I add promesa to the require list for a cljs namespace:

```
WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
return it__$1.catch(((function (it__$1){
              ^

WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
return p.finally(callback);
```

I've tried updating my `:language-in` and `:language-out` settings to be similar to what you're using in the script directory, but the warnings (which halt compilation on `:output :advanced`) persist. Any tips?

**Comment by niwinz** [comment]
I don't know that can be happening. The only stuff you should do is, put language-in to ecmascript5 in the same way as the scripts/build.clj file. Are you sure that you have put that settings properly?

You can check that promesa can be compiled with cljs just downloading the repository and execute the `scripts/build` script.

**Comment by mattly** [comment]
I'm using boot instead of lein, and while the problem persists with `{:language-in :ecmascript5 :language-out :ecmascript5}` as the `:compiler-options` for boot-cljs, as it happens my project has to support older browsers, so I _have_ to target `ecmascript3` instead.

**Comment by metametadata** [comment]
I've just encountered this error when compiling my project in advanced mode using `lein` and `cljsbuild`. Adding `:language-in :ecmascript5` into `:compiler` helped. 

The default for `:language-in/:language-out` is `:ecmascript3`. Why is lib compiled into `ecmascript5`?

**Comment by niwinz** [comment]
ecmascript3 does not allow use function names with language keywords such as "finally" and "catch", ecmascript5 removes that limitation. Promesa defines functions with that names, because of that, ecmascript5 should be used as language-in ;)

**Comment by metametadata** [comment]
Thanks!

I've also tried to fix the `promesa` build script. It looks like `promesa` can build itself with `:language-out :ecmascript3` without any warnings. But unfortunately, after `lein install`-ing the local snapshot and requiring it in my sample project it starts producing warnings again.
