### ISSUE TITLE
Missing properties in externs blocks advanced optimizations

### ISSUE THREAD

**Issue by ingesolvoll** [funcool/promesa#26]
When building my app for production, I get the following message when run:

Uncaught TypeError: Promise.Ci is not a function(anonymous function) @ app.js:891

The referred section of the code is:

var tF=Promise.Ci();tF.log(Ny,{cancellation:!0,warnings:!1},void 0);h=tF.prototype;h.Gg=f

I'm using httpurr 0.6.1 with promesa 1.4.0. The API from promesa referred to in my app is:

map
error
all
delay
resolved
alet
await

Any ideas?

**Comment by niwinz** [comment]
Very strange, are you sure that you are using the 1.4.0 version of promesa? Related issues to externs have been fixed in this last release... can you check it through the `lein deps :tree` ?

**Comment by ingesolvoll** [comment]
Yes, both `lein deps :tree` and `mvn dependency:tree` report promesa 1.4.0

**Comment by niwinz** [comment]
The problem is clearly related to this interop call: https://github.com/funcool/promesa/blob/master/src/promesa/impl/promise.cljc#L42

But it is already in externs so it should work. It can be for some reason there are other dependency that overwrites window.Promise ( js/Promise in cljs words) ? Can you chech in the chrome/mium devtools if bluebird.min.js is loaded and if window.Promise corresponds to bluebird promise? In summary it seems that something in your environment overwrites the required promise instance for some reasons that I can't understand without more information...

**Comment by ingesolvoll** [comment]
So something in my build process makes the closure compiler overlook Promise.noConflict?

I use maven for production builds, running clojurescript task in a script that looks like this:

```
(require 'cljs.build.api)

(cljs.build.api/build "src/main/cljs"
                      {:output-dir     "target/cljs-temp"
                       :output-to      "src/main/resources/public/js/compiled/app.js"
                       :optimizations  :advanced
                       :parallel-build true})
(System/exit 0)
```

**Comment by ingesolvoll** [comment]
I see that the minified bluebird 3.4.1 is included in app.js.

**Comment by ingesolvoll** [comment]
window.Property refers to bluebird.js source

**Comment by ingesolvoll** [comment]
Do I need to refer to the promesa externs file in my project build?

**Comment by niwinz** [comment]
No, you don't need to refer to it, because it is automatically included through `deps.cljs` of promesa.

**Comment by ingesolvoll** [comment]
Thanks for helping me on this, turns out that the issue was in my build. Changed to

```
(cljs.build.api/build (cljs.build.api/inputs "src/main/cljs" "src/main/cljc")
                      {:output-dir     "target/cljs-temp"
                       :output-to      "src/main/resources/public/js/compiled/app.js"
                       :optimizations  :advanced
                       :parallel-build true})
```

I do have cljc files in my client, and they were included before this change. But I suspect that dependencies with cljc files were not processed correctly.

**Comment by niwinz** [comment]
I'm glad that the issue is solved ;)
