### ISSUE TITLE
clj impl of core/finally adds no-arg callbacks

### ISSUE THREAD

**Issue by moea** [funcool/promesa#32]
https://github.com/funcool/promesa/blob/master/src/promesa/core.cljc#L175 looks like it adds callbacks in a such a way that'll cause an error when the promise completes.  Is the intention that the supplied callback receives no arguments, or receives the success/failure value?  (i.e. `(then (fn [_] (callback))` vs. `(then callback)`)

**Comment by niwinz** [comment]
Hmm seems like a bug...

**Comment by moea** [comment]
Happy to fix, just wasn't sure what the answer to the above question is.

**Comment by niwinz** [comment]
You are right, sorry for the quick read/answer. I don't know that is the best approach; if we take bluebird as example, its `finally` impl does not receive any arguments... on the other maybe it can be useful to people have the posibility to access the last value independently if it is exceptionally or successfully resolved...  what do you think about?

**Comment by moea** [comment]
I think it's possibly useful to receive the last value, but it might be awkward to adjust the cljs implementation to do something other than Bluebird's default behaviour - and since JS has weird error semantics, figuring out whether the promise succeeded or failed based on the `finally` value is probably not generally possible - so maybe no arguments makes more sense?

**Comment by niwinz** [comment]
agree with you that with no arguments is the way to go

**Comment by niwinz** [comment]
Fixed in master.
