### ISSUE TITLE
bind vs. then

### ISSUE THREAD

**Issue by moea** [funcool/promesa#35]
The way I use promesa, it'd be more convenient if the behaviour of `then` was to `bind` any promise returned by a callback.  The cost of having to wrap/disguise a promise which ought to be returned as-is seems worth paying, because I think that's a relatively rare use case.  

If that change would be too far-reaching, an alternative to `then` which binds if it encounters a promise would be just as helpful - or changing `bind` so it can accept functions which don't return promises, as well - basically I don't want to have to care whether a callback returns a promise or a resolved value.  What do you think?

**Comment by niwinz** [comment]
Sorry, but I'm not clearly understand that you trying to say.

**Comment by moea** [comment]
Apologies.

```clojure
(-> (p/resolved 5) (p/then (fn [x] (p/delay 1 (inc x)))) deref)
;; => #<Promise[value=6]>
```

I was saying I don't personally find that behaviour very helpful (I want `6` 99% of the time), because when assigning callbacks to promises, I currently have to worry about whether they themselves are asynchronous or not (and then use `bind`, rather than `then`, if they are).  This is made more awkward because `bind` requires a promise-returning callback (at least the clj implementation, I haven't checked cljs), so again, I have to know exactly what the callback is doing in order to apply it.

I was suggesting either a function like `bind` which can _also_ accept synchronous callbacks (i.e. ones returning immediate values), or extending `then` to behave like `bind` in the event that the callback is asynchronous.  Or just adding a separate function which does what I want.  Does that make sense?

**Comment by niwinz** [comment]
Hmm, then behaves like a map, with parameters inverted. Just for convenience and familiarity with existing js promise interface. If you want more "collections" like behavior, just use `p/map` and `p/mapcat` that corresponds to `map` and `bind`.

However, cljs impl differs from the clj. In cljs, js promises are used and they does not allow properly implement bind as is. The js promises has then that works as map and bind (if you return a promise in `.then` callback it will be unwrapped automatically, in the same way as you expect to work bind).

**Comment by moea** [comment]
Do you think unifying the behaviour between clj and cljs makes sense (I
guess by modifying the the clj implementation)? It seems like quite a
fundamental way for `then` to differ between platforms.

**Comment by niwinz** [comment]
I don't see the need to change the behavior. The cljs/js behavior is more inconsistent (but I can't change it without a lot of time inversion) and I don't want port that behavior to the clj. In fact `then` is a `map` with inverted parameters, just that.

I suggest don't using it and switch to `map` and `mapcat` ;)

**Comment by moea** [comment]
I understand - that's why map and mapcat have the same problem, from my perspective. I don't have an issue with the names, or the order of the parameters, I just don't really care whether any given callback is asynchronous - I always want `mapcat`/`bind` behaviour if a stage returns a promise, and always want `map`/`then` behaviour if it doesn't - I would imagine that wanting to return unresolved promises from promise callbacks (instead of unwrapping them) is a comparatively rare use case.

To me, `then` means _after the previous stage has completed_, regardless of whether the previous stage completed immediately.

```clojure
;; There may be a more efficient way to implement this directly w/ CompletableFuture, this
;; is just outlining the behaviour
(defn after [p f] 
  #?(:cljs (p/then p f) :clj (p/bind p #(cond-> % (not (p/promise? %)) p/resolved))))
```

If you don't agree that this behaviour is a reasonable replacement for `then`, do you feel perhaps that it's a utility worth including in promesa?

**Comment by niwinz** [comment]
My apologies, but It seems that I'm steel not understand that yo trying to say me. On the first instance i have understand that you want cljs/js behavior is clj impl, now I undertand that you want just the contrary...

In your last example, on clj impl, you never executes `f` so I'm not clearly understand the purpose of the `after` function.

At this moment in clj, the behavior is that the user expects:

```clojure
(p/map (fn [_] (p/resolved 2)) (p/resolved nil))
;; => #<Promise[value=java.util.concurrent.CompletableFuture@14a26260[Completed normally]]>
```

Map returns a promise that contains other promise, without unwrapping. This is expected behavior, in this cases you should use mapcat for properly unwrap it:

```clojure
(p/mapcat (fn [_] (p/resolved 2)) (p/resolved nil))
#<Promise[value=2]>
```

In clj, `then` is just an alias of `map` that changes the order of the parameters, nothing more.
At my understanding, there are 0 surprises behavior. I know that in cljs/js, this not behaves in the same way. It is implemented so just for pragmatic reasons. Implementing clj behavior on cljs will imply reimplement the promise implementation that is very costly for do it properly and archive the same performance as bluebird (the underlying promise impl used in cljs).

If something from previous examples is not working as you expect, please explain it with more details and simple examples of something that you are not expecting right now, and the behavior you want to have.

**Comment by moea** [comment]
Both of those examples work how I would expect.

I'm sorry to have wasted your time with my `after` example - that's what I get for writing code on my phone.  This is what I meant:

```clojure
(defn after [p f] 
  #?(:cljs (p/then p f)
      :clj (p/bind p (fn [in] 
                      (let [out (f in)] 
                        (if (p/promise? out) out (p/resolved out)))))))
```

This has the property that on both platforms:

```clojure
(-> (p/resolved 5) (after inc))
;; and
(-> (p/resolved 5) (after (comp p/resolved inc)))
```

do the same thing.  That's the behaviour I want - which is how `then` works in Clojurescript, as you said, and how e.g. Twisted, and a couple of other popular promise/deferred libraries handle callback application.

**Comment by niwinz** [comment]
Hmm interesting, now I understand that. So yes, I agree to modify the `then` behavior. PR is welcome ;)
