### ISSUE TITLE
.getValue and .getCause methods do not exist in bluebird Promise API

### ISSUE THREAD

**Issue by FongHou** [funcool/promesa#40]
Hi,
These two methods are used in extract protocol method. https://github.com/funcool/promesa/blob/master/src/promesa/impl.cljc#L65

They seem changed to .value and .reason (in bluebird 3.0?) 
http://bluebirdjs.com/docs/api/value.html

I did a local fix when troubleshooting an issue here. https://github.com/binaryage/dirac/issues/31

Thanks!

**Comment by niwinz** [comment]
Thanks!

**Comment by niwinz** [comment]
Fixed
