### ISSUE TITLE
Not all JS tests are executed

### ISSUE THREAD

**Issue by KrzysiekJ** [funcool/promesa#42]
## Steps to reproduce

```
./scripts/build
node out/tests.js
```

## What should happen

All tests should be executed.

## What actually happens

```
Testing promesa.issue-36

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
```

## Additional info

`node --version` returns “v6.9.4”.
`lein --version` returns “Leiningen 2.7.1 on Java 1.8.0_121 OpenJDK 64-Bit Server VM”.

**Comment by niwinz** [comment]
Thanks!

**Comment by niwinz** [comment]
Fixed
