### ISSUE TITLE
p/then is called even if the promise returned an error

### ISSUE THREAD

**Issue by JarrodCTaylor** [funcool/promesa#5]
In this example I expected that only the error would be logged. However, I also see the log generated in the `p/then`. Is this expected behavior?

``` clojure
(-> (p/promise (ex-info "Some error" nil))
      (p/catch (fn [error] (.log js/console error)))
      (p/then  (.log js/console "Why does this still happen?")))
```

**Comment by niwinz** [comment]
Yes. The catch operation, also returns a promise. So if the promise returned from the catch is a valid for resolved value the promise returned by catch will be resolved with the the return value.

This is a standard behavior in promises in javascript. And this behavior comes fro bluebird.

**Comment by JarrodCTaylor** [comment]
You are completely correct. Thanks for the input. Please disregard this.
