### ISSUE TITLE
undefined is not an object (evaluating 'promesa.core.alet.call')

### ISSUE THREAD

**Issue by lincoln-b** [funcool/promesa#50]
This is my code:

```
(require '[promesa.core :as p])

(def async-storage
  (goog.object/get (js/require "react-native") "AsyncStorage"))

(p/alet [item (p/await (.getItem async-storage app-key))] 
  item)
```

I'm just trying to mimic this JS syntax:

```
const value = await AsyncStorage.getItem(app-key);
```

I get this error:

![screen shot 2017-08-05 at 3 30 03 pm](https://user-images.githubusercontent.com/4949920/28998875-0c95266e-79f3-11e7-9aaa-b23d0f04ca38.png)

**Comment by fhur** [comment]
Hi @lincoln-b, let's see if I can help 😄 

A couple of things to keep in mind:

1. Notice that `p/await` expects a promise. I don't think that `(.getItem async-storage app-key)` returns a promise.
2. The following fragment

```
(p/alet [item (p/await (something-that-returns-a-promise args))] 
  item)
```

Is roughly equivalent to:

```
(let [item (p/promise (p/await (something-that-returns-a-promise args))]
  item)
```

Which is roughly equivalent to

```
(let [item (something-that-returns-a-promise args)]
  item)
```

**Comment by lincoln-b** [comment]
Yeah, my problem was that I thought p/await would block the main thread and wait for the promise to resolve. I realize now that's not possible (unsupported by JS).

I still don't know why that error was thrown but I just used straight JS syntax instead of promesa:

```
(-> (.getItem async-storage app-key)
    (.then #(js/alert %)))
```
