### ISSUE TITLE
Timeouts on Clojure?

### ISSUE THREAD

**Issue by jonathanj** [funcool/promesa#51]
I noticed the `timeout` function is behind a `cljs` reader conditional and there is no Java Clojure implementation. I realise you can use `deref` with a timeout but it's a bit jarring when considering the existing promise chaining design. Is there an alternative option I'm not seeing?

**Comment by niwinz** [comment]
No, there are no alternative option, it is just not implemented. PR is welcome for that part :D

**Comment by niwinz** [comment]
timeout is already implemented in clojure and will be released on 2.0.0 (`2.0.0-SNAPSHOT` is in clojars if you want to try it)
