### ISSUE TITLE
Bizarre loading failure 

### ISSUE THREAD

**Issue by cemerick** [funcool/promesa#52]
```
(require '[promesa.core :as pc])
Error: ENOENT: no such file or directory, open 'G:\dev\main\.cljs_node_replluebirdluebird.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.nodeGlobalRequire (repl:85:28)
    at Object.cljs$core$load_file [as load_file] (G:\dev\main\out\.cljs_node_repl\cljs\core.js:341:13)
```

This is using promesa `1.9.0`, Clojurescript `1.9.908`. I cannot reproduce under linux, so I assume this is a windows path problem? (`\\b` is an ascii control code escape sequence…)

**Comment by cemerick** [comment]
This was actually a node bug; updating to the latest LTS fixed me up.

**Comment by cemerick** [comment]
Okay, nvm, sorry; what I thought was fixed, isn't. The success I had was in a separate linux VM. (The usual late-night cognitive tax, I guess!)

The `promesa/impl.js` file that the compiler is writing out starts like so:

```js
// Compiled by ClojureScript 1.9.908 {:target :nodejs}
goog.provide('promesa.impl');
goog.require('cljs.core');
goog.require('promesa.protocols');
cljs.core.load_file(".cljs_node_repl\bluebird\bluebird.js");
```

Those unescaped `\b`'s are definitely a problem. This must be a compiler problem.

**Comment by niwinz** [comment]
Yeah, seems like a compiler problem. I suppose that you are using windows? In this case I can't help much here because I don't have windows environment :(

**Comment by cemerick** [comment]
I've got a patch ready for CLJS, putting the ticket in now.

**Comment by cemerick** [comment]
CLJS ticket + patch: https://dev.clojure.org/jira/browse/CLJS-2345

Not sure whether I should close this now or not. Definitely not promesa's problem, but leaving it open might be helpful for anyone else coming along until the fix is incorporated into a new CLJS release.

**Comment by niwinz** [comment]
Keep it open until cljs tiket is fixed.
Many thanks!

**Comment by niwinz** [comment]
Seems like is fixed now.
