### ISSUE TITLE
Lumo script with promesa

### ISSUE THREAD

**Issue by dupuchba** [funcool/promesa#53]
Hello friends, 

I am building a script for Lumo/Node using [puppeteer](https://github.com/GoogleChrome/puppeteer) which heavily use Promises.

I was looking for a more cljs way to handle Promise, I understand that `promesa` can help me with creating Promise but what about easily handling them ? Do you have any advices ?

Thanks a lot
Baptiste

**Comment by fhur** [comment]
What do you mean by easily handling them? If you give me an example or a better description of what you want to achieve I'll be happy to help

**Comment by dupuchba** [comment]
Ok, so let's take a pure JS example from the doc

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://news.ycombinator.com', {waitUntil: 'networkidle'});
  await page.pdf({path: 'hn.pdf', format: 'A4'});

  await browser.close();
})();;
```

This is one way to handle a pdf generation with the API.
BUT I would rather go with core.async or pure cljs function to handle everything, I don't know if it's possible right now.

**Comment by fhur** [comment]
Have you looked already into `promesa.core.promise` and `promesa.core.then`? It looks like that should have all you need to make this happen.

I would also recommend you take a look at the [alet](http://funcool.github.io/promesa/latest/#code-alet-code-macro-async-let) macro.

**Comment by eerohele** [comment]
Isn't the `alet` macro [only available in Clojure](https://github.com/funcool/promesa/blob/547d01652f335df18d4f2950efc8e7caba416fbb/src/promesa/core.cljc#L298-L315)?

I managed to generate a PDF like this:

```clojure
(require '[promesa.core :as promesa]
         '[puppeteer :as puppeteer])

(->> (.launch puppeteer)
     (promesa/map (fn [browser] (.newPage browser)))
     (promesa/map (fn [page]
                    (->> (.goto page "https://news.ycombinator.com" (clj->js {"waitUntil" "networkidle"}))
                         (promesa/map #(.pdf page (clj->js {"path" "hn.pdf" "format" "a4"})))))))
```

But that's missing the `browser.close()` call from the original version and probably isn't as clean as it could be. I'd certainly appreciate any feedback on how to improve the code.

**Comment by dupuchba** [comment]
I'll try today @eerohele

**Comment by eerohele** [comment]
FWIW, here's my `project.clj`:

```clojure
(defproject promesa-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[funcool/promesa "1.9.0"]]
  :main ^:skip-aot promesa-test.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}}
  :cljsbuild {:builds
              {:dev {:source-paths ["src"]
                     :compiler {:output-to "out/main.js"
                                :main some-ns.main
                                :target :nodejs}}}})
```

And here's my `package.json` (for [Yarn](https://yarnpkg.com/lang/en/)):

```json
{
  "dependencies": {
    "puppeteer": "^0.10.2"
  },

  "resolutions": {
    "mkdirp": "^0.5.1"
  }
}
```

And I'm running the code from a [Calvin](https://github.com/eginez/calvin) REPL.

(I don't know how to run the code from a `cljs` file so that it can find the Promesa dependency.)

**Comment by dupuchba** [comment]
@eerohele you don't require clojure & clojurescript ?

**Comment by eerohele** [comment]
Well, Lumo is a standalone ClojureScript environment, so I don't need to. The `project.clj` file is only used by Calvin to resolve the Promesa dependency. I don't need Clojure for anything since I'm trying to write a pure ClojureScript application.

**Comment by foopang** [comment]
How can I use async/await syntax? Below is my failed attempt.

```cljs
(ns app.main
  (:require [promesa.async-cljs :refer-macros [async]]
            [promesa.core :as p]))
            
(def puppeteer (js/require "puppeteer"))

(async
 (let [browser (p/await (.launch puppeteer))]
   (js/console.log (p/await (.version browser)))))
```


```
Unhandled rejection Error: kill ESRCH                                     
    at exports._errnoException (util.js:1022:11)                          
    at process.kill (internal/process.js:173:13)                          
    at killChrome (/home/me/cljs-test/target/node_modules/puppeteer/lib/Launcher.js:122:19)
    at Function.launch (/home/me/cljs-test/target/node_modules/puppeteer/lib/Launcher.js:108:7)
...
```

**Comment by niwinz** [comment]
This library is expect to work on clojurescript compilled by the jvm compiller. The promesa macros are probably not compatible with self-hosted environment (I never tryed it there).

**Comment by arichiardi** [comment]
Has anyone done any work on the port? Just want to see if I am stepping on someone's toes :smile:

**Comment by didibus** [comment]
To work with self-hosted, it will also need to use the self-hosted core.async, sounds like a big change. Not sure how the dependency could be made to switch between one and the other.

**Comment by arichiardi** [comment]
I know this I know this :smile: 

This is how I do it in another place https://github.com/clojure-emacs/cljs-tooling/pull/24/files#diff-0fff143854a4f5c0469a3819b978a483R13

**Comment by bhurlow** [comment]
has anyone tried porting promesa to work with self-hosted core.async (andare)? Seems like it should work

**Comment by niwinz** [comment]
I think this issue is no longer relevant because we no longer have core.async dependency,
