### ISSUE TITLE
Async macro exception handling

### ISSUE THREAD

**Issue by mjmeintjes** [funcool/promesa#56]
Not sure if this is a bug or just me not understanding it correctly.

When using the async macro in ClojureScript, I am unable to handle thrown exceptions. I've tried attaching a (p/catch) handler to the value returned from the async macro, as well as wrapping the p/await call inside a try/catch block, but any exceptions thrown during a p/await call goes unhandled.

The p/catch function does get called, but I still also get an Unhandled rejection error.

**Comment by fhur** [comment]
Hi @mjmeintjes, it would be really helpful if you could supply us with a code snippet that reproduces the bug.

**Comment by mjmeintjes** [comment]
Sure. The following code is for ClojureScript running under NodeJs.
Code:
```
(ns mattsum.bug-test.core
  (:require
   [promesa.core :as p]
   [promesa.async-cljs :refer-macros [async]]))

(defn throw-ex
  []
  (-> (p/promise 0)
      (p/then (fn [_]
                (throw (ex-info "TEST" {}))))))
(->
 (async
  (println "STARTING")
  (p/await (throw-ex))
  (println "STARTED"))
 (p/catch (fn [err]
            (println "CAUGHT" err))))
(defn main [& cli-args]
  (prn "hello world" cli-args))
```
When I run this, I would expect the following output:
```
"hello world" nil
STARTING
CAUGHT #error {:message TEST, :data {}}
```
Instead, I get the following output:
```
"hello world" nil
STARTING
Unhandled rejection Error: TEST ....(lots of additional stacktrace)....
```

**Comment by niwinz** [comment]
Yeah, is a bug. I have a fix for clojurescript ready, working on the clojure part.

**Comment by Satshabad** [comment]
Having the same issue as well, trying to catch within an alet binding doesn't seem to work.

**Comment by niwinz** [comment]
Finally found a way to fix it on bot side. Fix already in master and will be available on the next release.
