### ISSUE TITLE
Protocol extension problem on js/Promise

### ISSUE THREAD

**Issue by arichiardi** [funcool/promesa#58]
Hello folks!

I am working on [the sieppari port to ClojureScript](https://github.com/metosin/sieppari/pull/10) and  running into some trouble: there is a protocol on `js/Promise` that seem to disappear when I require `promesa.core`.

Now, I am not an expert here but if I recall correctly bluebird does some magic there and I was wondering if there is a way for the two promise types to coexist or maybe I just need to extend the protocol on the right object.

The native Promise extend is [here](https://github.com/metosin/sieppari/pull/10/files#diff-ea653724690ce6faf457b78bd891c557R41) while the promesa one is [here](https://github.com/metosin/sieppari/pull/10/files#diff-fc1548418287893bf71a7c4426902c58R15).

Thank you very much in advance!

**Comment by niwinz** [comment]
This is the consecuence of using `noConflict` in promesa. It is used for not pullute the global object with own internal protocols. That approach is not strictly necesarry, is just a good default, but if this causes more troubles that solutons we maybe need to relax that.

**Comment by arichiardi** [comment]
So the workaround I found it to redefine the native promise protocol after requiring the promesa namespace.

You can see it here: https://github.com/arichiardi/sieppari/blob/70a52b87ada8afebdcfe5e9310ab2170b8d6f0ea/src/sieppari/async/promesa.cljc

**Comment by arichiardi** [comment]
So yeah, side effects in require are always a bit brittle but I see why promesa would do that: you normally don't want to use anything else then bluebird promises...

I keep reading the [noConflict](http://bluebirdjs.com/docs/api/promise.noconflict.html) to understand what removing that implies and if it would be a breaking change (I would bump minor just in case to be honest).

I can patch and remove that line if you are ok with it.

**Comment by niwinz** [comment]
I think this not make any breaking change, i'm using this `noConflict` for not "forcing" the user always use bluebird promise. This is the only reason to use `noConflict`. But seems that makes more problems that solutions.

I pushed the changes to master and released the `1.10.0-SNAPSHOT` to clojars. Please, can you try it without your workaround and (probably) confirm my hipotesis.

**Comment by arichiardi** [comment]
I will definitely try shortly. Thank you for the fix!

**Comment by arichiardi** [comment]
It seemed to work, all tests pass in this commit: https://github.com/arichiardi/sieppari/commit/4a8439a899d436a7199758b680afb8917f9cc38c
