### ISSUE TITLE
Consider publishing no-bluebird build

### ISSUE THREAD

**Issue by skrat** [funcool/promesa#59]
I think it would be great to have the choice to use this great library (and other ones depending on it) without having to pull in bluebird.js and instead use the native implementation. We would just need a different build target excluding `/assets` and the `require` in `core.cljc`; also removal of the `(js/Promise.noConflict) call` and having it published under, eg. `funcool/promesa-nobb`

**Comment by niwinz** [comment]
The downside of this is that default Promise does not support introspection (there are no methods like `isRejected`, `reason`, `value`, `isPending` ...) so the IState protocol will be completly useless on js...This is the main reason to choice the bluebird promise instead of default one. I need to think how to make this stuff optional.

**Comment by skrat** [comment]
I think you may have at most 2 choices here (when the user selects native impl):

1. let if fail with not-implemented
2. somehow implement the state on the native promise, perhaps by adding your own internal callbacks. I'm not a promise expert, and am not sure if this is possible

**Comment by niwinz** [comment]
The second option is imposible, if the promise comes from an external library, there now way to know the promise state.

I'm thinking that by default it will raise a not implemented error is the unique solution...

**Comment by niwinz** [comment]
The good news, that the performance of native promises is improved and memory usage also improved.
I'll try to take some time this week for remove bluebird hard dependency :D

**Comment by skrat** [comment]
I think it's wort it to keep bluebird to be easily enabled. Not sure how to do this though because once you include `deps.cljs` there's no easy way to disable the bundling. Perhaps have a look at the npm integration and externs inference.

**Comment by niwinz** [comment]
I have in mind, some functions: `set-promise!` allowing the user use an other impl than the default, dcument an example on how to enable bluebird promises on the user code (with an example on how extend the `IState` protocol if is needed, it is not necessary in normal promise use cases). This will make the library more lightweight and finally allow the user decide which promise impl to use. Is a good balance i think.

**Comment by niwinz** [comment]
Initial approach is landed in `2.0.0-SNAPSHOT` that already comes without bluebird.

**Comment by nha** [comment]
my tests pass with `2.0.0-SNAPSHOT` (not a huge test suite though)

**Comment by arichiardi** [comment]
Opened a [PR against sieppari](https://github.com/metosin/sieppari/pull/16) so that we also make sure that is not breaking. Thanks, looking forward to `promesa` `2.0.0`!

**Comment by niwinz** [comment]
I'm testing the promesa on my internal projects. I hope i will release the 2.0.0 soon if no regression found. Please tell me how it behaves on your projects and if you found any issues.

**Comment by pepe** [comment]
In my project I am using it just a little, but everything seems to work as advertised.

**Comment by niwinz** [comment]
The 2.0.0 is released.
