### ISSUE TITLE
Docs page can't be loaded because of stylesheet.css

### ISSUE THREAD

**Issue by alexander-yakushev** [funcool/promesa#65]
https://www.niwi.nz/_assets/asciidoctor-styles/simple-red-titles/stylesheet.css can't be loaded which makes the documentation site http://funcool.github.io/promesa/latest/ render poorly or not at all.

**Comment by niwinz** [comment]
Fixed

**Comment by wizpig64** [comment]
stylesheet.css is 404'd again, and the docs over at django-jinja rely on it, too: http://niwinz.github.io/django-jinja/latest/

@niwinz i found your asciidoctor-styles repo with the source, and i'm working on a pull request to bring the django-jinja docs branch up to date. would it be a bad idea to serve that stylesheet.css right in the gh-pages branch? I'm brand new at using asciidoctor, but it looks pretty straightforward.
