### ISSUE TITLE
Does not play well with JS promises

### ISSUE THREAD

**Issue by divs1210** [funcool/promesa#66]
Promesa promises don't play well with JS promises. I keep getting protocol errors and having to wrap JS promises inside promesa promises inside JS promises and so on.

Thank you for your work, but please put a huge disclaimer somewhere so that others don't end up wasting as much time as I did.

No promise library > false promise library.

**Comment by niwinz** [comment]
@divs1210 Can you provide a concrete case where `promesa` doesn't play well with native promises? 

Right now promesa works with native promises as default implementation (no external dependencies) (**in the past** we used bluebird and there are some problems with native promises)

And promesa is used in many projects working with native JS promises so that you saying sounds strange... If you can provide more info about your problem maybe I can help you.

**Comment by divs1210** [comment]
Thanks for the reply.
I might have been doing something wrong.
Will get back with an example.

**Comment by divs1210** [comment]
I am using [nodegit](https://github.com/nodegit/nodegit).

Code:
```clojure
(defonce Git
  (js/require "nodegit"))

(defonce Repository
  (.-Repository Git))
```
Repl:
```clojure
git> (p/alet [repo-promise (.open Repository "/path/to/repo")
                     repo (p/await repo-promise)]
                    repo)
Error: No protocol method IPromise.-bind defined for type object: [object Object]
    at Object.cljs$core$missing_protocol [as missing_protocol] (target/js/compiled/dev/cljs-runtime/cljs/core.cljs:312:3)
    at Object.cljs.core/missing-protocol [as _bind] (target/js/compiled/dev/cljs-runtime/promesa/protocols.cljc:28:1)
    at promesa$core$bind (target/js/compiled/dev/cljs-runtime/promesa/core.cljc:139:1)
    at <eval>:3:26
    at cljsEval (<eval>:12:3)
```

**Comment by niwinz** [comment]
I have tested that, and You are right. There are something that nodegit does that does not returns an instance of the same promise as js/Promise (the global node promise). 

Look this:
```clojure
cljs.user=> (def x (.open repo "/home/niwi/tmp/react/"))
#'cljs.user/x
cljs.user=> (def y (js/Promise. (fn [res])))
#'cljs.user/y
cljs.user=> x
#object[Promise [object Object]]
cljs.user=> y
#<Promise[~]>
```
You can see that the promise returned by the nodegit looks different that the global js/Promise instance... The are nothing that i can do from promesa side. If nodegit returns that promises...

My recommendation is, create a specific functions that wraps the specific stuff that you are using from nodegit and use them...

**Comment by divs1210** [comment]
I rolled my own `async`/`await` macros:
```clojure
(ns more.async
  (:refer-clojure :exclude [await]))

(defmacro ->chan
  [promise]
  `(let [ch# (cljs.core.async/chan)]
     (.then ~promise
            #(cljs.core.async.macros/go (cljs.core.async/>! ch# %)))
     ch#))

(defmacro async
  [& body]
  `(~'js/Promise.
    (fn [resolve#]
      (cljs.core.async.macros/go
        (resolve# (let []
                    ~@body))))))

(defmacro await
  [promise]
  `(cljs.core.async/<! (->chan ~promise)))
```
These work with both normal JS promises as well as the nodegit ones.

**Comment by niwinz** [comment]
Yeah, but you are completly ignoring the error part of the promise. But if it is ok for you, that is nice ;)

**Comment by divs1210** [comment]
Shouldn't be too hard when I do need them. Much better than raw promises.

**Comment by niwinz** [comment]
The 3.0.0-SNAPSHOT incudes a fix that probably fix this problem.

**Comment by jsa-aerial** [comment]
@niwinz 

ClojureScript: Any idea why this doesn't work:

```Clojure
(let [pv (p/do!
          (let [a (rand-int 10)
                b (rand-int 10)]
            (+ a b)))]
  (p/extract pv))
```
=> `#object[Error Error: No protocol method IState.-extract defined for type object: [object Promise]]`

```Clojure
(let [pv (p/do!
          (let [a (rand-int 10)
                b (rand-int 10)]
            (+ a b)))]
  pv)
```
=> #<Promise[~]>
```Clojure
(type *1)
```
=> #object[Promise]

Also, you can wrap in a p/promise and it still fails.  Also, things like p/resolve! and p/resolved? fail for the same reason - no protocols defined

**Comment by niwinz** [comment]
the synchronous extraction in javascript execution environment is not posible because the underlying type does not supports it (the native Promise object does not supports it) so there are no way to get the value synchronously in cljs...

**Comment by jsa-aerial** [comment]
OK makes some sense (JS is truly a pain in this whole area).  Is it possible to 'await' a promise using promesa - other than just giving up and using `.then`.  Old examples indicate that there used to be a `p/await`, but that is no longer there.

**Comment by niwinz** [comment]
You have the `p/let` macro for this purpose:

```clojure
(p/let [a (function-that-return-promise)]
  (println "result:" a))
```
you already have good constructions for not needing in absolutly the await stuff.
