### ISSUE TITLE
Isn't enough documents for ClojureScript

### ISSUE THREAD

**Issue by kangbb** [funcool/promesa#69]
How do we use `async/await` in ClojureScript?
I only see Cojure. How should I do?

**Comment by niwinz** [comment]
What is not clear in the doc (http://funcool.github.io/promesa/latest/#asyncawait-syntax)

PD: this is not native js async/await, this is a syntactic sugar done using macros. So there no native async/await in clojurescript.

**Comment by kangbb** [comment]
> What is not clear in the doc (http://funcool.github.io/promesa/latest/#asyncawait-syntax)
> 
> PD: this is not native js async/await, this is a syntactic sugar done using macros. So there no native async/await in clojurescript.

Actually, the latest version `3.0.0` doesn't work for your linked docs, I can't find `async` in the `promesa.core`. And the `alet` looks like doesn't work for `cljs`.

**Comment by niwinz** [comment]
- the 3.0.0, removes the `async` macro (look at changelog)
- `alet` works perfectly on clojurescript, there are many tests that checks that for clojurescript and for clojure; if you have some troble, please report a isolated test case for it please.
- the documentation linked is updated, refresh many times it maybe for some reason your browser or github caches it...

**Comment by kangbb** [comment]
> * the 3.0.0, removes the `async` macro (look at changelog)
> * `alet` works perfectly on clojurescript, there are many tests that checks that for clojurescript and for clojure; I have many projeces in cljs already using `alet` with promesa 3.0.0; if you have some troble, please report a isolated test case for it, please.
> * the documentation linked is updated, refresh many times it maybe for some reason your browser or github caches it...

**Comment by kangbb** [comment]
Thank you, I will try them again.
