### ISSUE TITLE
kitchen-async style p/do

### ISSUE THREAD

**Issue by martinklepsch** [funcool/promesa#70]
What I'm looking for is a simple way to run multiple promise-returning forms sequentially, e.g.:

```clj
(require '[kitchen-async.promise :as ka])
(ka/do 
 (if (> (rand) 0.5)
   (do (println "delaying 1s")
       (p/delay 1000))
   (do (println "delaying 3s")
       (p/delay 3000)))
 (println "done1")
 (p/delay 1000)
 (println "done2"))
```

This would print the different lines with some delays. Does promesa have an API for this kind of thing or is it not really in the scope of the project? 

There is `do*` in promesa but I don't fully understand the docstrings of that and `attempt`. Some quick testing with the example above suggested that it's meant for something different. 

edit: Oh and **thanks for all the amazing recent work on promesa**, I really appreciate it's lightweightness after bluebird was dropped and the well maintained changelog! 👍 

--- 

Somewhat relatedly I have this in a project I'm currently working on — would be curious if there's more elegant ways to handle this using promisa's APIs.

```clj
(defn doall-serial
  "Apply `f` to every element in `xs`, chaining all the returned promises so
  that every element is processed one by one and not in parallel.

  It is expected that `f` returns a promise. Kind of like doseq."
  [f xs]
  (loop [[x & xs] xs
         p (p/resolve nil)]
    (when x
      (recur
       xs
       (-> p
           (p/then (fn [] (f x)))
           (p/catch* (fn [err]
                       (js/console.error err)
                       (throw err))))))))
```

**Comment by niwinz** [comment]
Hello @martinklepsch !
I have looked into the kitchen-async macros and many of they are look very nice. Many of them are clearly on scope of promesa. Thanks for the suggestion!

About `doall-serial`: if you can elaborate more on it (example use, use case,...) we can work on it to include on promesa if it loos enough general purpose :D 

Thanks!

**Comment by niwinz** [comment]
Right now if you want the same way functionality of the kitchen-async p/do, you can use the let in this way:

```clojure
(p/alet [_ (expr1)
         _ (expr 2)
         _ (expr 3)]
  (expr4))
```

That clearly can be translated to the `do` macro.

**Comment by niwinz** [comment]
I already have the `do*` macro replacement. As the current `do*` macro is practically useless, i will replace it with the new one and release a new major...

```clojure
(def pfn (fn [x] (prn "pfn:" x) (p/promise x)))

(p/then (p/do* (pfn 1) (pfn 2) (pfn 3)) #(prn "result:" %))
;; => "pfn:" 1
;; => "pfn:" 2
;; => "pfn:" 3
;; => "result:" 3
```

**Comment by niwinz** [comment]
bumped 4.0.0-SNAPSHOT with that changes, changelog and doc updated (in the source only, not published to gh-pages).

**Comment by martinklepsch** [comment]
Amazing, that was blazingly quick 🙌 

Re: `doall-serial`:

```clj
(doall-serial
  (fn [n]
    (p/then (p/delay n) #(println n "ms passed")))
  [1000 2000 3000])

;; 1000ms pass ...
;; => "1000 ms passed"
;; 2000ms pass ...
;; => "2000 ms passed"
;; 3000ms pass ...
;; => "3000 ms passed"

;; In total 6s passed when "3000 ms passed" was printed
```

Hope this makes sense 😄

**Comment by niwinz** [comment]
The most similar think that i find in clojure that does the same thing  is `run!` function. So I made the `run!` function (promise aware):

```clojure
(defn run!
  "A promise aware run! function."
  [f coll]
  (reduce (fn [acc o]
            (bind acc (fn [_]
                          (pt/-promise (f o)))))
          (pt/-promise nil)
          coll))
```

```clojure
(p/then (p/run! (fn [i] (p/then (p/delay i) #(prn "item:" % i))) [1000 2000 3000])
        #(prn "finished" %))
;; => "item:" nil 1000
;; => "item:" nil 2000
;; => "item:" nil 3000
;; => "finished" nil

**Comment by martinklepsch** [comment]
Fantastic! Thanks so much, both of these will be very helpful in migrating to promesa.

**Comment by martinklepsch** [comment]
@niwinz just FYI, `run!` is currently still missing from the changelog.

**Comment by niwinz** [comment]
@martinklepsch thanks for the reminder
