### ISSUE TITLE
`finally` doesn't work with spec Promises

### ISSUE THREAD

**Issue by dregre** [funcool/promesa#71]
`finally` [relies on the existence of a `.lastly` method on Promises](https://github.com/funcool/promesa/blob/master/src/promesa/core.cljc#L211), but that method [isn't spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).  You're probably looking for [`.finally`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally).  Note that this method was added relatively recently:  as of Chrome 63 and Node 10.

**Comment by niwinz** [comment]
Fixed on master.
