### ISSUE TITLE
docs using @ to dereference promise - not working with cljs on nodejs

### ISSUE THREAD

**Issue by fdhenard** [funcool/promesa#73]
I'm attempting to use promesa with cljs on nodejs.  The docs seem to be using @ to "resolve" the promise and get the value.  Am I understanding that correctly?  I ask because that doesn't seem to be working for me.

**Comment by niwinz** [comment]
yes, this is only works on jvm, js does not have any way to block waiting promise resolution.

**Comment by niwinz** [comment]
The examples in the documentation are mainly for jvm, in some examples specifies that @ syntax is only on jvm and is used for convenience.

**Comment by fdhenard** [comment]
Understood, thanks!
