### ISSUE TITLE
Exceptions don't get caught by "catch" when thrown in "promise" body

### ISSUE THREAD

**Issue by olivermg** [funcool/promesa#77]
I noticed that thrown exceptions apparently don't get caught by `catch` clauses when they are thrown from within the `promise` body:

```
(-> (p/promise (throw (ex-info "foo" {})))
    (p/catch (fn [e] (println "ERROR" e))))
```

results in an (unexpectedly) uncaught exception:

```
Execution error (ExceptionInfo) at user/eval61083 (form-init3437190804973754551.clj:1).
foo
class clojure.lang.ExceptionInfo
  form-init3437190804973754551.clj:	1	user/eval61083
  form-init3437190804973754551.clj:	1	user/eval61083
  Compiler.java:	7177	clojure.lang.Compiler/eval
  Compiler.java:	7132	clojure.lang.Compiler/eval
  core.clj:	3214	clojure.core/eval
...
```

Contrary to that, when the exception gets thrown from within `then`, it does get caught by the `catch` clause:

```
(-> (p/promise nil)
    (p/then (fn [_] (throw (ex-info "foo" {}))))
    (p/catch (fn [e] (println "ERROR" e))))
```

results in the (expected) behavior:

```
ERROR #error {
 :cause foo
 :data {}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message foo
   :data {}
   :at [user$eval61087$fn__61088 invoke form-init3437190804973754551.clj 2]}]
 :trace
 [[user$eval61087$fn__61088 invoke form-init3437190804973754551.clj 2]
  [clojure.core$comp$fn__5807 invoke core.clj 2569]
  [promesa.util.FunctionWrapper apply util.cljc 43]
...
  [java.lang.Thread run Thread.java 748]]}

#object[java.util.concurrent.CompletableFuture 0x65ecd6d "resolved"]
```

Am I missing anything?

**Comment by niwinz** [comment]
yep

The `promise` is not a macro, is just a function that receives a value and coerces it to promise. So in your case:

```clojure
(p/promise (throw (ex-info "foo" {})))
```
the `promise` function never get to see the value, because the exception is raised before create the promise. I suspect that you want is a promise "constructor" that catches all the exception inside. For this case you have the `p/create` promise factory and the `p/do!` macro.

Examples:

```clojure
(-> (p/create (fn [resolve, reject] (reject (ex-info "foo" {}))))
    (p/catch (fn [e] (println "ERROR" e))))

;; or

(-> (p/do! (throw (ex-info "foo" {})))
    (p/catch (fn [e] (println "ERROR" e))))

**Comment by olivermg** [comment]
Thanks for the quick response and suggestions, I'll probably use `do!` then in my case.

However, this behavior caught me off guard, as I was expecting that `promise` would be able to handle exceptions.

**Comment by niwinz** [comment]
it handles, but in your example the exception is happens outside of the promise...
