### ISSUE TITLE
Java 12 CompletionStage.exceptionallyAsync method is used

### ISSUE THREAD

**Issue by yaronel** [funcool/promesa#80]
I am getting a reflection warning when compiling my project using promesa:
```
Reflection warning, promesa/impl.cljc:178:11 - call to method exceptionallyAsync on java.util.concurrent.CompletionStage can't be resolved (no such method).
```
The method was introduces in Java 12.

The docs say:
```
On the JVM paltform promesa is built on top of completable futures (requires jdk>=8)
```

**Comment by niwinz** [comment]
Yes this method only affects one specific method execution when you use `catch'` with a custom executor. In this case jdk12 is required, is a documentation bug, and this method is not commonly used. Unfortunatelly the warning can't be disabled.
