### ISSUE TITLE
Strange errors while using promesa with code that throw

### ISSUE THREAD

**Issue by mauricioszabo** [funcool/promesa#86]
Why does the following code does not compile?

```clojure
(p/do!
  (p/delay 2000)
  (throw (ex-info "fail" {})))
```
It always fail to compile with the error:

```
 245 |           (p/do!
------------------^-------------------------------------------------------------
 Use of undeclared Var <current-namespace>/ignore
--------------------------------------------------------------------------------
```

**Comment by niwinz** [comment]
Looks something unrelarelated to promesa, becaise promesa does not have nothing called `ignore` inside the `do!` macro

**Comment by p-himik** [comment]
@mauricioszabo Were you using shadow-cljs when that happened, by any chance?

**Comment by mauricioszabo** [comment]
@p-himik yes, I was.

**Comment by p-himik** [comment]
Good, because I could reproduce it only there. :) After some investigation, I've notified thheller about it: https://clojurians.slack.com/archives/C6N245JGG/p1643740157399209

**Comment by niwinz** [comment]
So I closing this one, thanks for all the work and research about this issue.
