### ISSUE TITLE
map function not working with collection argument

### ISSUE THREAD

**Issue by burinc** [funcool/promesa#87]
When trying the simple `map` function I got the following result:

```clojure
(p/then (->> (p/resolved [1 2 3])
             (p/map inc))
         prn)
```
The result:

```clojure
"[1 2 3]1" 
```
Use with single value it works properly

```clojure
(p/then (->> (p/resolved 3)
              (p/map inc))
         prn)
```
The result

```clojure
4
```
Could this be a bug?

**Comment by niwinz** [comment]
Hi @burinc,
No, it is intended behavior, you are not maping over collection, you are mapping over promise that contains a collection, so in the first example you are just executing `(inc [1 2 3])`.

**Comment by burinc** [comment]
@niwinz  thanks for clarification. Make sense.
