### ISSUE TITLE
Shouldn't (promesa.core/finally) use JS Promise .finally() instead of being a synonym for .then() ?

### ISSUE THREAD

**Issue by raymond-w-ko** [funcool/promesa#88]
https://github.com/funcool/promesa/blob/147c15974484a4f3634e6ad095217806dbb58ee4/src/promesa/impl.cljc#L100

Or is `Promise.finally()` too new?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

**Comment by niwinz** [comment]
hmm probably
This was done when finally didnt existed on js side. Probably using it right now may make sense.

**Comment by niwinz** [comment]
After looking on this, the `finally` method cant be implemented in terms of Promise.finally, because it does not return neither result or error.
