### ISSUE TITLE
Suggestion: make a protocol to `p/promise?` 

### ISSUE THREAD

**Issue by mauricioszabo** [funcool/promesa#89]
Hi, first of all, thanks a lot for this project - it's wonderful to work with ClojureScript with it!

So, I've been using promesa most of my projects, and in some cases I have to add extension points to the user. I found that `p/promise?` checks only for specific classes, both on Clojure and ClojureScript, and there's no other way to check if a specific object is indistinguishable from a `promesa`'s  promise.

So what do you think about adding a protocol, that anyone can implement, so that their library "works as" a promise? This could bring different implementations of futures like Twitter's Futures, Scala's Futures, maybe even Akka or other libs, and make then work exactly the same as Promesa. WDYT?

Let me know if you want examples, or a specific use-case, etc.

**Comment by niwinz** [comment]
Hmm, I'm open to a pre for this! I think it will be useful

**Comment by niwinz** [comment]
This shold be solved, promise? now checks for IPromise protocol instead of concrete type.

**Comment by niwinz** [comment]
Reverted because the change was wrong, i will address it soon in other revision.

**Comment by niwinz** [comment]
Finally fixed
