### ISSUE TITLE
Applying non-functions

### ISSUE THREAD

**Issue by moea** [funcool/promesa#9]
Is it reasonable to expect this to work the same in cljs as it does on the JVM?

```clojure
(-> {:x 1} p/promise (p/then :x))
```

Similarly for multimethods, and I guess everything which does evaluate to `Function`.  One naive fix would be to have `-map`, `-bind` and `-catch` wrap all inputs in `fn` - do you think that's a bad idea?  More than happy to make the change, if not.

**Comment by niwinz** [comment]
Great idea! The change is very welcome!
