### ISSUE TITLE
p/promise instead of p/create in user guide

### ISSUE THREAD

**Issue by geekarist** [funcool/promesa#93]
About the user guide in the section "Promise Composition" / let: 

Shouldn't it be `p/create` instead of `p/promise` here?

```clojure
(defn sleep-promise
  [wait]
  (p/promise (fn [resolve reject]
               (exec/schedule! wait #(resolve wait)))))
```

**Comment by niwinz** [comment]
You are right, thanks, i will fix it on my next commit.
