### ISSUE TITLE
Incorrect documentation in the "Error handling" section

### ISSUE THREAD

**Issue by p-himik** [funcool/promesa#95]
At https://cljdoc.org/d/funcool/promesa/6.0.2/doc/user-guide#error-handling the documentation says:
> If some computation inside the composed promise chain/pipeline raises an exception, the pipeline short-circuits and propogates the exception to the last promise in the chain.

Apart from the type in the word "propagates", the sentence makes it seem as if in a chain like `promise -> reject -> catch -> then` the resulting promise will be rejected. But this is not the case when `catch` returns a regular value. The pipeline never short-circuits - it just skips nearest `then` handlers for thrown exceptions or rejected promises and skips nearest `catch` handlers for properly returned values or resolved promises.

**Comment by niwinz** [comment]
The typo fixed, thanks.
The expression i think is correct because it does not explains how catch works, it explains how error is handled as-is, without any error handling. The catch is the tool for handle it and not propagate.

**Comment by niwinz** [comment]
In any case I improve the current doc.
Thanks.
